### PR TITLE
Fix build with base-4.13.0.0

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Review by amcphail — CHANGES_REQUESTED** [review]
Thank you.

Can you please bump the minor version number in the cabal file and add a note to CHANGES?

Cheers,

Vivian

**Comment by JackTheEngineer** [comment]
Sorry to nag about this here, but it seems like both of you are either too busy or too proud to change two lines of code. 
It would be really nice, if stackage got the compiling update of plot, as it is a very nice package.
Thank you for creating it, Vivian !
Should I open a new pull request with the bumped number and a note to changes ?

Best regard, 
JackTheEngineer

**Comment by amcphail** [comment]
Hi Jack,

If you could do that it would be great.  I thought that it would be cleaner
to have it all in one pull request.  I'll check when I get to the office
tomorrow and take care of it either way.

Cheers,

Vivian

**Comment by hasufell** [comment]
>  I thought that it would be cleaner
> to have it all in one pull request.  I'll check when I get to the office
> tomorrow and take care of it either way.
> 

You can push to other peoples pull requests, so everything can be in one PR.

I believe release preparation should best be left to the maintainers.

**Pull request merged**
