### PR TITLE
Add support for plotting vector functions, which may be faster to eva…

### PR DESCRIPTION
**Pull request by alang9**
…luate than plain functions

### CODE REVIEW

**Comment by amcphail** [comment]
Unfortunately, these changes get rid of 'normal' functions in favour of `Vector Double -> Vector Double` so would break exisiting code.

New vector functionality should build on top of current functionality, not replace it.

**Comment by alang9** [comment]
I don't think this gets rid of any old functionality. Notice that all the `Ordinate` instance based on `Function` are still there

**Comment by amcphail** [comment]
```
-data Ordinates = OrdFunction AxisSide Function  (Maybe SeriesLabel)
+data Ordinates = OrdFunction AxisSide FunctionV (Maybe SeriesLabel)
                | OrdPoints   AxisSide OrdSeries (Maybe SeriesLabel)
```

But I see what you're saying.

**Comment by amcphail** [comment]
Okay.  Can you change `FunctionV` to `VectorFunction`.  Just a minor change and then I'll merge the pull request.

**Comment by alang9** [comment]
Done

**Pull request merged**
